### ISSUE TITLE
Using OpenOCD with GDB in pipe mode

### ISSUE THREAD

**Issue by zxawry** [Palmitoxico/STM32F103_Template#2] opened 2020-01-01 17:25 UTC
I tried to use the debug script in the repository and encountered the same error as you discussed [here](https://sourceforge.net/p/openocd/mailman/message/36264531/), after awhile I reckoned the culprit lies in the `openocd.cfg` where it prompts the selected interface and so it interferes with the GDB connection. Removing the following line resolved this issue for me:
https://github.com/Palmitoxico/STM32F103_Template/blob/19c740b2ab838221eb9d41f7e76247fc529c2a1f/openocd.cfg#L27
 Also I think addition of event handlers for GDB attach/detach would make this template more beginner friendly which I tried to add as follows:
```
stm32f1x.cpu configure -event gdb-attach { reset init }
stm32f1x.cpu configure -event gdb-detach { reset run }
```

**Comment by augustofg** [comment] 2020-01-03 13:52
Nice catch!

It seems that the ```puts``` tcl command always writes to stdout, even when the ```gdb_port``` is set to ```pipe```, thus messing up the communication between gdb and openocd. I've replaced with the ```echo``` command, as it writes to the log output (which can be redirected to a file).

Regarding the gdb attach and detach events, I would avoid resetting the target because some times you want to connect to the target without disturbing its state (important for some hard to reproduce bugs).

Please look at ed57ff526b3a3a4109ec4654fbcfd5c869d748ef, 4f5eb1464eed603f8e09e84e90f9865d46e3ffa6 and 4dfb5ebff49e4516dc56f0e2423838361fee48ac.

Thanks!
Augusto.

**Comment by zxawry** [comment] 2020-01-03 15:16
I do agree with your comment on GDB attach/detach events and it's better not to reset the target, only a subtle fix for https://github.com/Palmitoxico/STM32F103_Template/commit/4dfb5ebff49e4516dc56f0e2423838361fee48ac as `run` needs to be replaced with `resume` in the event handler according to this [manual](http://openocd.org/doc/html/General-Commands.html).

**Comment by augustofg** [comment] 2020-01-03 17:33
You are right, fixed it on master.

I'm closing this issue, thanks for the input.

Augusto.

**Closed as completed by augustofg** 2020-01-03 17:33 UTC

**Comment by zxawry** [comment] 2020-01-03 18:04
You're most welcome. Thank you as well for creating and maintaining this neat template.
